server:
  port: 6080
spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    naming-strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
  flyway:
    enabled: false
